### ISSUE TITLE
installation failes with duojs (0.6 as well as 0.5)

### ISSUE THREAD

**Issue by mbykov** [treojs/treo#35]
$ make build/index.js                                                                       (git)-[master] 

     building : client/index.js
        using : compatibility
        using : stoj
    installed : treojs-treo@0.6.0
        error : Error: unable to resolve ./idb-store@*
    at get (/usr/local/lib/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/lib/github.js:135:13)
    at GeneratorFunctionPrototype.next (native)
    at Duo.next (/usr/local/lib/node_modules/duo/node_modules/co/index.js:74:21)
    at Duo.<anonymous> (/usr/local/lib/node_modules/duo/node_modules/co/index.js:93:18)
    at Immediate._onImmediate (/usr/local/lib/node_modules/duo/node_modules/co/index.js:52:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by alekseykulikov** [comment]
I don't know, how duo works, but component.json should use dist/treo.js and don't try to resolve any dependencies. If this is not possible, treo depends on a bunch of modules, and I'm not going to add & support component.json to each of them

**Comment by mbykov** [comment]
ok, thank you
